baseurl: '/sunday-game-brunch'
permalink: pretty
prose:
  rooturl: '_posts'
  siteurl: 'http://dennerkrans.github.io/sunday-game-brunch/'
  relativeLinks: 'http://dennerkrans.github.io/sunday-game-brunch/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          value: "false"
      - name: "category"
        field:
          element: "select"
          label: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "General information"
              value: "General information"
            - name: "Items"
              value: "items"
            - name: "Locations"
              value: "Locations"
            - name: "Lore"
              value: "Lore"
            - name: "NPC"
              value: "Npc"
            - name: "Players"
              value: "Players"
            - name: "Quests"
              value: "Quests"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Magic"
              value: "magic"
            - name: "Undead"
              value: "undead"
            - name: "Important"
              value: "important"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""
    _posts/character:
      - name: "layout"
        field:
          element: "hidden"
          value: "character"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          value: "false"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "character-name"
        field:
          element: "text"
          label: "Character name"
          value: ""
      - name: "player"
        field:
          element: "text"
          label: "Player"
          value: ""
      - name: "class"
        field:
          element: "text"
          label: "Class"
          value: ""
      - name: "race"
        field:
          element: "text"
          label: "Race"
          value: ""
      - name: "background"
        field:
          element: "text"
          label: "Background"
          value: ""
      - name: "trinket"
        field:
          element: "text"
          label: "Trinket"
          value: ""
      - name: "portrait"
        field:
          element: "text"
          label: Portrait
          placeholder: "Paste url to portrait image"
          value: ""
      - name: "category"
        field:
          element: "select"
          label: "Add Category"
          placeholder: "Choose Category"
          options:
            - name: "NPC"
              value: "NPC"
            - name: "Player"
              value: "Player"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
